/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'publishedAt' : Timestamp,
  'targetClasses' : Array<string>,
  'teacherPrincipal' : Principal,
}
export type ApiResult = { 'ok' : TimetableEntry } |
  { 'err' : string };
export type ApiResult_1 = { 'ok' : HomeworkSubmission } |
  { 'err' : string };
export type ApiResult_2 = { 'ok' : TeacherProfile } |
  { 'err' : string };
export type ApiResult_3 = { 'ok' : StudentProfile } |
  { 'err' : string };
export type ApiResult_4 = { 'ok' : ChatMessage } |
  { 'err' : string };
export type ApiResult_5 = { 'ok' : HomeworkAssignment } |
  { 'err' : string };
export type ApiResult_6 = { 'ok' : Announcement } |
  { 'err' : string };
export type ApiResult_7 = { 'ok' : Array<HomeworkSubmission> } |
  { 'err' : string };
export type ApiResult_8 = { 'ok' : Array<StudentProfile> } |
  { 'err' : string };
export interface AttendanceRecord {
  'studentId' : StudentId,
  'markedVia' : string,
  'present' : boolean,
  'date' : DateText,
}
export interface ChatMessage {
  'id' : bigint,
  'content' : string,
  'subject' : string,
  'sentAt' : Timestamp,
  'senderPrincipal' : Principal,
  'senderName' : string,
}
export type DateText = string;
export interface HomeworkAssignment {
  'id' : bigint,
  'title' : string,
  'subject' : string,
  'createdAt' : Timestamp,
  'dueDate' : string,
  'description' : string,
  'assignedClasses' : Array<string>,
  'teacherPrincipal' : Principal,
}
export interface HomeworkSubmission {
  'id' : bigint,
  'status' : SubmissionStatus,
  'homeworkId' : bigint,
  'studentPrincipal' : Principal,
  'submittedAt' : Timestamp,
  'submittedContent' : string,
}
export interface Student {
  'id' : StudentId,
  'subjects' : Array<string>,
  'name' : string,
  'className' : string,
  'streakCount' : bigint,
  'avatar' : string,
}
export type StudentId = string;
export interface StudentProfile {
  'parent2Contact' : [] | [string],
  'principal' : Principal,
  'dateOfBirth' : [] | [string],
  'name' : string,
  'parent1Name' : [] | [string],
  'academicMedium' : [] | [string],
  'email' : string,
  'schoolAddress' : [] | [string],
  'bloodGroup' : [] | [string],
  'rollNumber' : string,
  'gender' : [] | [string],
  'schoolTiming' : [] | [string],
  'board' : [] | [string],
  'livingAddress' : [] | [string],
  'parent1Contact' : [] | [string],
  'className' : string,
  'parent2Name' : [] | [string],
  'schoolName' : [] | [string],
}
export interface StudyStreak {
  'studentId' : StudentId,
  'lastStudyDate' : DateText,
  'longestStreak' : bigint,
  'currentStreak' : bigint,
}
export interface StudyTask {
  'id' : string,
  'title' : string,
  'studentId' : StudentId,
  'subject' : string,
  'completed' : boolean,
  'dueDate' : DateText,
  'priority' : string,
}
export interface SubjectProgress {
  'studentId' : StudentId,
  'subject' : string,
  'weeklyScores' : Array<bigint>,
  'currentPercentage' : bigint,
}
export type SubmissionStatus = { 'graded' : null } |
  { 'submitted' : null } |
  { 'pending' : null };
export interface TeacherProfile {
  'bio' : string,
  'principal' : Principal,
  'subjects' : Array<string>,
  'name' : string,
  'contactPhone' : string,
}
export type Timestamp = bigint;
export interface TimetableEntry {
  'id' : bigint,
  'startTime' : string,
  'subject' : string,
  'endTime' : string,
  'dayOfWeek' : string,
  'teacherPrincipal' : Principal,
  'className' : string,
}
export type UserRole = { 'teacher' : null } |
  { 'unregistered' : null } |
  { 'student' : null };
export interface _SERVICE {
  'completeTask' : ActorMethod<[string], boolean>,
  'getAnnouncements' : ActorMethod<[string], Array<Announcement>>,
  'getAttendance' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getHomeworkByClass' : ActorMethod<[string], Array<HomeworkAssignment>>,
  'getMessages' : ActorMethod<[string], Array<ChatMessage>>,
  'getMyProfile' : ActorMethod<
    [],
    [] | [{ 'teacher' : TeacherProfile } | { 'student' : StudentProfile }]
  >,
  'getMyRole' : ActorMethod<[], UserRole>,
  'getStreak' : ActorMethod<[string], [] | [StudyStreak]>,
  'getStudentList' : ActorMethod<[], ApiResult_8>,
  'getStudentProfile' : ActorMethod<[string], [] | [Student]>,
  'getStudyTasks' : ActorMethod<[string], Array<StudyTask>>,
  'getSubjectProgress' : ActorMethod<[string], Array<SubjectProgress>>,
  'getSubmissions' : ActorMethod<[bigint], ApiResult_7>,
  'getTimetable' : ActorMethod<[string], Array<TimetableEntry>>,
  'listAllTeachers' : ActorMethod<[], Array<TeacherProfile>>,
  'markAttendance' : ActorMethod<[string, string, string], boolean>,
  'postAnnouncement' : ActorMethod<
    [string, string, Array<string>],
    ApiResult_6
  >,
  'postHomework' : ActorMethod<
    [string, string, string, string, Array<string>],
    ApiResult_5
  >,
  'postMessage' : ActorMethod<[string, string], ApiResult_4>,
  'registerStudent' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    ApiResult_3
  >,
  'registerTeacher' : ActorMethod<
    [string, Array<string>, string, string],
    ApiResult_2
  >,
  'seedDemoData' : ActorMethod<[], undefined>,
  'seedTeachers' : ActorMethod<[], undefined>,
  'submitHomework' : ActorMethod<[bigint, string], ApiResult_1>,
  'updateTimetable' : ActorMethod<[TimetableEntry], ApiResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];