/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'publishedAt' : Timestamp,
  'targetClasses' : IDL.Vec(IDL.Text),
  'teacherPrincipal' : IDL.Principal,
});
export const StudentId = IDL.Text;
export const DateText = IDL.Text;
export const AttendanceRecord = IDL.Record({
  'studentId' : StudentId,
  'markedVia' : IDL.Text,
  'present' : IDL.Bool,
  'date' : DateText,
});
export const HomeworkAssignment = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'createdAt' : Timestamp,
  'dueDate' : IDL.Text,
  'description' : IDL.Text,
  'assignedClasses' : IDL.Vec(IDL.Text),
  'teacherPrincipal' : IDL.Principal,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'subject' : IDL.Text,
  'sentAt' : Timestamp,
  'senderPrincipal' : IDL.Principal,
  'senderName' : IDL.Text,
});
export const TeacherProfile = IDL.Record({
  'bio' : IDL.Text,
  'principal' : IDL.Principal,
  'subjects' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const StudentProfile = IDL.Record({
  'parent2Contact' : IDL.Opt(IDL.Text),
  'principal' : IDL.Principal,
  'dateOfBirth' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'parent1Name' : IDL.Opt(IDL.Text),
  'academicMedium' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'schoolAddress' : IDL.Opt(IDL.Text),
  'bloodGroup' : IDL.Opt(IDL.Text),
  'rollNumber' : IDL.Text,
  'gender' : IDL.Opt(IDL.Text),
  'schoolTiming' : IDL.Opt(IDL.Text),
  'board' : IDL.Opt(IDL.Text),
  'livingAddress' : IDL.Opt(IDL.Text),
  'parent1Contact' : IDL.Opt(IDL.Text),
  'className' : IDL.Text,
  'parent2Name' : IDL.Opt(IDL.Text),
  'schoolName' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'teacher' : IDL.Null,
  'unregistered' : IDL.Null,
  'student' : IDL.Null,
});
export const StudyStreak = IDL.Record({
  'studentId' : StudentId,
  'lastStudyDate' : DateText,
  'longestStreak' : IDL.Nat,
  'currentStreak' : IDL.Nat,
});
export const ApiResult_8 = IDL.Variant({
  'ok' : IDL.Vec(StudentProfile),
  'err' : IDL.Text,
});
export const Student = IDL.Record({
  'id' : StudentId,
  'subjects' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'className' : IDL.Text,
  'streakCount' : IDL.Nat,
  'avatar' : IDL.Text,
});
export const StudyTask = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'studentId' : StudentId,
  'subject' : IDL.Text,
  'completed' : IDL.Bool,
  'dueDate' : DateText,
  'priority' : IDL.Text,
});
export const SubjectProgress = IDL.Record({
  'studentId' : StudentId,
  'subject' : IDL.Text,
  'weeklyScores' : IDL.Vec(IDL.Nat),
  'currentPercentage' : IDL.Nat,
});
export const SubmissionStatus = IDL.Variant({
  'graded' : IDL.Null,
  'submitted' : IDL.Null,
  'pending' : IDL.Null,
});
export const HomeworkSubmission = IDL.Record({
  'id' : IDL.Nat,
  'status' : SubmissionStatus,
  'homeworkId' : IDL.Nat,
  'studentPrincipal' : IDL.Principal,
  'submittedAt' : Timestamp,
  'submittedContent' : IDL.Text,
});
export const ApiResult_7 = IDL.Variant({
  'ok' : IDL.Vec(HomeworkSubmission),
  'err' : IDL.Text,
});
export const TimetableEntry = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Text,
  'subject' : IDL.Text,
  'endTime' : IDL.Text,
  'dayOfWeek' : IDL.Text,
  'teacherPrincipal' : IDL.Principal,
  'className' : IDL.Text,
});
export const ApiResult_6 = IDL.Variant({
  'ok' : Announcement,
  'err' : IDL.Text,
});
export const ApiResult_5 = IDL.Variant({
  'ok' : HomeworkAssignment,
  'err' : IDL.Text,
});
export const ApiResult_4 = IDL.Variant({
  'ok' : ChatMessage,
  'err' : IDL.Text,
});
export const ApiResult_3 = IDL.Variant({
  'ok' : StudentProfile,
  'err' : IDL.Text,
});
export const ApiResult_2 = IDL.Variant({
  'ok' : TeacherProfile,
  'err' : IDL.Text,
});
export const ApiResult_1 = IDL.Variant({
  'ok' : HomeworkSubmission,
  'err' : IDL.Text,
});
export const ApiResult = IDL.Variant({
  'ok' : TimetableEntry,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'completeTask' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAnnouncements' : IDL.Func([IDL.Text], [IDL.Vec(Announcement)], ['query']),
  'getAttendance' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getHomeworkByClass' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(HomeworkAssignment)],
      ['query'],
    ),
  'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
  'getMyProfile' : IDL.Func(
      [],
      [
        IDL.Opt(
          IDL.Variant({
            'teacher' : TeacherProfile,
            'student' : StudentProfile,
          })
        ),
      ],
      ['query'],
    ),
  'getMyRole' : IDL.Func([], [UserRole], ['query']),
  'getStreak' : IDL.Func([IDL.Text], [IDL.Opt(StudyStreak)], ['query']),
  'getStudentList' : IDL.Func([], [ApiResult_8], ['query']),
  'getStudentProfile' : IDL.Func([IDL.Text], [IDL.Opt(Student)], ['query']),
  'getStudyTasks' : IDL.Func([IDL.Text], [IDL.Vec(StudyTask)], ['query']),
  'getSubjectProgress' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SubjectProgress)],
      ['query'],
    ),
  'getSubmissions' : IDL.Func([IDL.Nat], [ApiResult_7], ['query']),
  'getTimetable' : IDL.Func([IDL.Text], [IDL.Vec(TimetableEntry)], ['query']),
  'listAllTeachers' : IDL.Func([], [IDL.Vec(TeacherProfile)], ['query']),
  'markAttendance' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'postAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [ApiResult_6],
      [],
    ),
  'postHomework' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [ApiResult_5],
      [],
    ),
  'postMessage' : IDL.Func([IDL.Text, IDL.Text], [ApiResult_4], []),
  'registerStudent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [ApiResult_3],
      [],
    ),
  'registerTeacher' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
      [ApiResult_2],
      [],
    ),
  'seedDemoData' : IDL.Func([], [], []),
  'seedTeachers' : IDL.Func([], [], []),
  'submitHomework' : IDL.Func([IDL.Nat, IDL.Text], [ApiResult_1], []),
  'updateTimetable' : IDL.Func([TimetableEntry], [ApiResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'publishedAt' : Timestamp,
    'targetClasses' : IDL.Vec(IDL.Text),
    'teacherPrincipal' : IDL.Principal,
  });
  const StudentId = IDL.Text;
  const DateText = IDL.Text;
  const AttendanceRecord = IDL.Record({
    'studentId' : StudentId,
    'markedVia' : IDL.Text,
    'present' : IDL.Bool,
    'date' : DateText,
  });
  const HomeworkAssignment = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'createdAt' : Timestamp,
    'dueDate' : IDL.Text,
    'description' : IDL.Text,
    'assignedClasses' : IDL.Vec(IDL.Text),
    'teacherPrincipal' : IDL.Principal,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'subject' : IDL.Text,
    'sentAt' : Timestamp,
    'senderPrincipal' : IDL.Principal,
    'senderName' : IDL.Text,
  });
  const TeacherProfile = IDL.Record({
    'bio' : IDL.Text,
    'principal' : IDL.Principal,
    'subjects' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const StudentProfile = IDL.Record({
    'parent2Contact' : IDL.Opt(IDL.Text),
    'principal' : IDL.Principal,
    'dateOfBirth' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'parent1Name' : IDL.Opt(IDL.Text),
    'academicMedium' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'schoolAddress' : IDL.Opt(IDL.Text),
    'bloodGroup' : IDL.Opt(IDL.Text),
    'rollNumber' : IDL.Text,
    'gender' : IDL.Opt(IDL.Text),
    'schoolTiming' : IDL.Opt(IDL.Text),
    'board' : IDL.Opt(IDL.Text),
    'livingAddress' : IDL.Opt(IDL.Text),
    'parent1Contact' : IDL.Opt(IDL.Text),
    'className' : IDL.Text,
    'parent2Name' : IDL.Opt(IDL.Text),
    'schoolName' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'teacher' : IDL.Null,
    'unregistered' : IDL.Null,
    'student' : IDL.Null,
  });
  const StudyStreak = IDL.Record({
    'studentId' : StudentId,
    'lastStudyDate' : DateText,
    'longestStreak' : IDL.Nat,
    'currentStreak' : IDL.Nat,
  });
  const ApiResult_8 = IDL.Variant({
    'ok' : IDL.Vec(StudentProfile),
    'err' : IDL.Text,
  });
  const Student = IDL.Record({
    'id' : StudentId,
    'subjects' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'className' : IDL.Text,
    'streakCount' : IDL.Nat,
    'avatar' : IDL.Text,
  });
  const StudyTask = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'studentId' : StudentId,
    'subject' : IDL.Text,
    'completed' : IDL.Bool,
    'dueDate' : DateText,
    'priority' : IDL.Text,
  });
  const SubjectProgress = IDL.Record({
    'studentId' : StudentId,
    'subject' : IDL.Text,
    'weeklyScores' : IDL.Vec(IDL.Nat),
    'currentPercentage' : IDL.Nat,
  });
  const SubmissionStatus = IDL.Variant({
    'graded' : IDL.Null,
    'submitted' : IDL.Null,
    'pending' : IDL.Null,
  });
  const HomeworkSubmission = IDL.Record({
    'id' : IDL.Nat,
    'status' : SubmissionStatus,
    'homeworkId' : IDL.Nat,
    'studentPrincipal' : IDL.Principal,
    'submittedAt' : Timestamp,
    'submittedContent' : IDL.Text,
  });
  const ApiResult_7 = IDL.Variant({
    'ok' : IDL.Vec(HomeworkSubmission),
    'err' : IDL.Text,
  });
  const TimetableEntry = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Text,
    'subject' : IDL.Text,
    'endTime' : IDL.Text,
    'dayOfWeek' : IDL.Text,
    'teacherPrincipal' : IDL.Principal,
    'className' : IDL.Text,
  });
  const ApiResult_6 = IDL.Variant({ 'ok' : Announcement, 'err' : IDL.Text });
  const ApiResult_5 = IDL.Variant({
    'ok' : HomeworkAssignment,
    'err' : IDL.Text,
  });
  const ApiResult_4 = IDL.Variant({ 'ok' : ChatMessage, 'err' : IDL.Text });
  const ApiResult_3 = IDL.Variant({ 'ok' : StudentProfile, 'err' : IDL.Text });
  const ApiResult_2 = IDL.Variant({ 'ok' : TeacherProfile, 'err' : IDL.Text });
  const ApiResult_1 = IDL.Variant({
    'ok' : HomeworkSubmission,
    'err' : IDL.Text,
  });
  const ApiResult = IDL.Variant({ 'ok' : TimetableEntry, 'err' : IDL.Text });
  
  return IDL.Service({
    'completeTask' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAnnouncements' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Announcement)],
        ['query'],
      ),
    'getAttendance' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getHomeworkByClass' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HomeworkAssignment)],
        ['query'],
      ),
    'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
    'getMyProfile' : IDL.Func(
        [],
        [
          IDL.Opt(
            IDL.Variant({
              'teacher' : TeacherProfile,
              'student' : StudentProfile,
            })
          ),
        ],
        ['query'],
      ),
    'getMyRole' : IDL.Func([], [UserRole], ['query']),
    'getStreak' : IDL.Func([IDL.Text], [IDL.Opt(StudyStreak)], ['query']),
    'getStudentList' : IDL.Func([], [ApiResult_8], ['query']),
    'getStudentProfile' : IDL.Func([IDL.Text], [IDL.Opt(Student)], ['query']),
    'getStudyTasks' : IDL.Func([IDL.Text], [IDL.Vec(StudyTask)], ['query']),
    'getSubjectProgress' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SubjectProgress)],
        ['query'],
      ),
    'getSubmissions' : IDL.Func([IDL.Nat], [ApiResult_7], ['query']),
    'getTimetable' : IDL.Func([IDL.Text], [IDL.Vec(TimetableEntry)], ['query']),
    'listAllTeachers' : IDL.Func([], [IDL.Vec(TeacherProfile)], ['query']),
    'markAttendance' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'postAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [ApiResult_6],
        [],
      ),
    'postHomework' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [ApiResult_5],
        [],
      ),
    'postMessage' : IDL.Func([IDL.Text, IDL.Text], [ApiResult_4], []),
    'registerStudent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [ApiResult_3],
        [],
      ),
    'registerTeacher' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
        [ApiResult_2],
        [],
      ),
    'seedDemoData' : IDL.Func([], [], []),
    'seedTeachers' : IDL.Func([], [], []),
    'submitHomework' : IDL.Func([IDL.Nat, IDL.Text], [ApiResult_1], []),
    'updateTimetable' : IDL.Func([TimetableEntry], [ApiResult], []),
  });
};

export const init = ({ IDL }) => { return []; };