/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface HomeworkSubmission {
    id: bigint;
    status: SubmissionStatus;
    homeworkId: bigint;
    studentPrincipal: Principal;
    submittedAt: Timestamp;
    submittedContent: string;
}
export type ApiResult_7 = {
    __kind__: "ok";
    ok: Array<HomeworkSubmission>;
} | {
    __kind__: "err";
    err: string;
};
export type ApiResult_3 = {
    __kind__: "ok";
    ok: StudentProfile;
} | {
    __kind__: "err";
    err: string;
};
export type ApiResult = {
    __kind__: "ok";
    ok: TimetableEntry;
} | {
    __kind__: "err";
    err: string;
};
export type ApiResult_2 = {
    __kind__: "ok";
    ok: TeacherProfile;
} | {
    __kind__: "err";
    err: string;
};
export interface TimetableEntry {
    id: bigint;
    startTime: string;
    subject: string;
    endTime: string;
    dayOfWeek: string;
    teacherPrincipal: Principal;
    className: string;
}
export interface SubjectProgress {
    studentId: StudentId;
    subject: string;
    weeklyScores: Array<bigint>;
    currentPercentage: bigint;
}
export interface StudyTask {
    id: string;
    title: string;
    studentId: StudentId;
    subject: string;
    completed: boolean;
    dueDate: DateText;
    priority: string;
}
export type StudentId = string;
export interface TeacherProfile {
    bio: string;
    principal: Principal;
    subjects: Array<string>;
    name: string;
    contactPhone: string;
}
export type ApiResult_6 = {
    __kind__: "ok";
    ok: Announcement;
} | {
    __kind__: "err";
    err: string;
};
export type ApiResult_5 = {
    __kind__: "ok";
    ok: HomeworkAssignment;
} | {
    __kind__: "err";
    err: string;
};
export interface StudentProfile {
    parent2Contact?: string;
    principal: Principal;
    dateOfBirth?: string;
    name: string;
    parent1Name?: string;
    academicMedium?: string;
    email: string;
    schoolAddress?: string;
    bloodGroup?: string;
    rollNumber: string;
    gender?: string;
    schoolTiming?: string;
    board?: string;
    livingAddress?: string;
    parent1Contact?: string;
    className: string;
    parent2Name?: string;
    schoolName?: string;
}
export interface HomeworkAssignment {
    id: bigint;
    title: string;
    subject: string;
    createdAt: Timestamp;
    dueDate: string;
    description: string;
    assignedClasses: Array<string>;
    teacherPrincipal: Principal;
}
export type ApiResult_8 = {
    __kind__: "ok";
    ok: Array<StudentProfile>;
} | {
    __kind__: "err";
    err: string;
};
export type ApiResult_1 = {
    __kind__: "ok";
    ok: HomeworkSubmission;
} | {
    __kind__: "err";
    err: string;
};
export type DateText = string;
export interface Announcement {
    id: bigint;
    title: string;
    body: string;
    publishedAt: Timestamp;
    targetClasses: Array<string>;
    teacherPrincipal: Principal;
}
export interface ChatMessage {
    id: bigint;
    content: string;
    subject: string;
    sentAt: Timestamp;
    senderPrincipal: Principal;
    senderName: string;
}
export interface StudyStreak {
    studentId: StudentId;
    lastStudyDate: DateText;
    longestStreak: bigint;
    currentStreak: bigint;
}
export interface AttendanceRecord {
    studentId: StudentId;
    markedVia: string;
    present: boolean;
    date: DateText;
}
export type ApiResult_4 = {
    __kind__: "ok";
    ok: ChatMessage;
} | {
    __kind__: "err";
    err: string;
};
export interface Student {
    id: StudentId;
    subjects: Array<string>;
    name: string;
    className: string;
    streakCount: bigint;
    avatar: string;
}
export enum SubmissionStatus {
    graded = "graded",
    submitted = "submitted",
    pending = "pending"
}
export enum UserRole {
    teacher = "teacher",
    unregistered = "unregistered",
    student = "student"
}
export interface backendInterface {
    completeTask(taskId: string): Promise<boolean>;
    getAnnouncements(className: string): Promise<Array<Announcement>>;
    getAttendance(studentId: string): Promise<Array<AttendanceRecord>>;
    getHomeworkByClass(className: string): Promise<Array<HomeworkAssignment>>;
    getMessages(subject: string): Promise<Array<ChatMessage>>;
    getMyProfile(): Promise<{
        __kind__: "teacher";
        teacher: TeacherProfile;
    } | {
        __kind__: "student";
        student: StudentProfile;
    } | null>;
    getMyRole(): Promise<UserRole>;
    getStreak(studentId: string): Promise<StudyStreak | null>;
    getStudentList(): Promise<ApiResult_8>;
    getStudentProfile(studentId: string): Promise<Student | null>;
    getStudyTasks(studentId: string): Promise<Array<StudyTask>>;
    getSubjectProgress(studentId: string): Promise<Array<SubjectProgress>>;
    getSubmissions(homeworkId: bigint): Promise<ApiResult_7>;
    getTimetable(className: string): Promise<Array<TimetableEntry>>;
    listAllTeachers(): Promise<Array<TeacherProfile>>;
    markAttendance(studentId: string, date: string, via: string): Promise<boolean>;
    postAnnouncement(title: string, body: string, targetClasses: Array<string>): Promise<ApiResult_6>;
    postHomework(subject: string, title: string, description: string, dueDate: string, assignedClasses: Array<string>): Promise<ApiResult_5>;
    postMessage(content: string, subject: string): Promise<ApiResult_4>;
    registerStudent(name: string, className: string, email: string, rollNumber: string, board: string | null, academicMedium: string | null, livingAddress: string | null, schoolName: string | null, schoolAddress: string | null, parent1Name: string | null, parent1Contact: string | null, parent2Name: string | null, parent2Contact: string | null, schoolTiming: string | null, dateOfBirth: string | null, gender: string | null, bloodGroup: string | null): Promise<ApiResult_3>;
    registerTeacher(name: string, subjects: Array<string>, contactPhone: string, bio: string): Promise<ApiResult_2>;
    seedDemoData(): Promise<void>;
    seedTeachers(): Promise<void>;
    submitHomework(homeworkId: bigint, submittedContent: string): Promise<ApiResult_1>;
    updateTimetable(entry: TimetableEntry): Promise<ApiResult>;
}
import type { Announcement as _Announcement, ApiResult as _ApiResult, ApiResult_1 as _ApiResult_1, ApiResult_2 as _ApiResult_2, ApiResult_3 as _ApiResult_3, ApiResult_4 as _ApiResult_4, ApiResult_5 as _ApiResult_5, ApiResult_6 as _ApiResult_6, ApiResult_7 as _ApiResult_7, ApiResult_8 as _ApiResult_8, ChatMessage as _ChatMessage, HomeworkAssignment as _HomeworkAssignment, HomeworkSubmission as _HomeworkSubmission, Student as _Student, StudentProfile as _StudentProfile, StudyStreak as _StudyStreak, SubmissionStatus as _SubmissionStatus, TeacherProfile as _TeacherProfile, Timestamp as _Timestamp, TimetableEntry as _TimetableEntry, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async completeTask(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.completeTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeTask(arg0);
            return result;
        }
    }
    async getAnnouncements(arg0: string): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnnouncements(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnnouncements(arg0);
            return result;
        }
    }
    async getAttendance(arg0: string): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendance(arg0);
            return result;
        }
    }
    async getHomeworkByClass(arg0: string): Promise<Array<HomeworkAssignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHomeworkByClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHomeworkByClass(arg0);
            return result;
        }
    }
    async getMessages(arg0: string): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return result;
        }
    }
    async getMyProfile(): Promise<{
        __kind__: "teacher";
        teacher: TeacherProfile;
    } | {
        __kind__: "student";
        student: StudentProfile;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRole();
                return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRole();
            return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStreak(arg0: string): Promise<StudyStreak | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStreak(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStreak(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentList(): Promise<ApiResult_8> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentList();
                return from_candid_ApiResult_8_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentList();
            return from_candid_ApiResult_8_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentProfile(arg0: string): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudyTasks(arg0: string): Promise<Array<StudyTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudyTasks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudyTasks(arg0);
            return result;
        }
    }
    async getSubjectProgress(arg0: string): Promise<Array<SubjectProgress>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubjectProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubjectProgress(arg0);
            return result;
        }
    }
    async getSubmissions(arg0: bigint): Promise<ApiResult_7> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissions(arg0);
                return from_candid_ApiResult_7_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissions(arg0);
            return from_candid_ApiResult_7_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTimetable(arg0: string): Promise<Array<TimetableEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimetable(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimetable(arg0);
            return result;
        }
    }
    async listAllTeachers(): Promise<Array<TeacherProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllTeachers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllTeachers();
            return result;
        }
    }
    async markAttendance(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markAttendance(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAttendance(arg0, arg1, arg2);
            return result;
        }
    }
    async postAnnouncement(arg0: string, arg1: string, arg2: Array<string>): Promise<ApiResult_6> {
        if (this.processError) {
            try {
                const result = await this.actor.postAnnouncement(arg0, arg1, arg2);
                return from_candid_ApiResult_6_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postAnnouncement(arg0, arg1, arg2);
            return from_candid_ApiResult_6_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async postHomework(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<string>): Promise<ApiResult_5> {
        if (this.processError) {
            try {
                const result = await this.actor.postHomework(arg0, arg1, arg2, arg3, arg4);
                return from_candid_ApiResult_5_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postHomework(arg0, arg1, arg2, arg3, arg4);
            return from_candid_ApiResult_5_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async postMessage(arg0: string, arg1: string): Promise<ApiResult_4> {
        if (this.processError) {
            try {
                const result = await this.actor.postMessage(arg0, arg1);
                return from_candid_ApiResult_4_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postMessage(arg0, arg1);
            return from_candid_ApiResult_4_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerStudent(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string | null, arg5: string | null, arg6: string | null, arg7: string | null, arg8: string | null, arg9: string | null, arg10: string | null, arg11: string | null, arg12: string | null, arg13: string | null, arg14: string | null, arg15: string | null, arg16: string | null): Promise<ApiResult_3> {
        if (this.processError) {
            try {
                const result = await this.actor.registerStudent(arg0, arg1, arg2, arg3, to_candid_opt_n26(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg12), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg13), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg14), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg15), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg16));
                return from_candid_ApiResult_3_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerStudent(arg0, arg1, arg2, arg3, to_candid_opt_n26(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg12), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg13), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg14), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg15), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg16));
            return from_candid_ApiResult_3_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerTeacher(arg0: string, arg1: Array<string>, arg2: string, arg3: string): Promise<ApiResult_2> {
        if (this.processError) {
            try {
                const result = await this.actor.registerTeacher(arg0, arg1, arg2, arg3);
                return from_candid_ApiResult_2_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerTeacher(arg0, arg1, arg2, arg3);
            return from_candid_ApiResult_2_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedDemoData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedDemoData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedDemoData();
            return result;
        }
    }
    async seedTeachers(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedTeachers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedTeachers();
            return result;
        }
    }
    async submitHomework(arg0: bigint, arg1: string): Promise<ApiResult_1> {
        if (this.processError) {
            try {
                const result = await this.actor.submitHomework(arg0, arg1);
                return from_candid_ApiResult_1_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitHomework(arg0, arg1);
            return from_candid_ApiResult_1_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTimetable(arg0: TimetableEntry): Promise<ApiResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTimetable(arg0);
                return from_candid_ApiResult_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTimetable(arg0);
            return from_candid_ApiResult_n33(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ApiResult_1_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiResult_1): ApiResult_1 {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_ApiResult_2_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiResult_2): ApiResult_2 {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_ApiResult_3_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiResult_3): ApiResult_3 {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_ApiResult_4_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiResult_4): ApiResult_4 {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_ApiResult_5_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiResult_5): ApiResult_5 {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_ApiResult_6_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiResult_6): ApiResult_6 {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ApiResult_7_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiResult_7): ApiResult_7 {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ApiResult_8_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiResult_8): ApiResult_8 {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_ApiResult_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiResult): ApiResult {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_HomeworkSubmission_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HomeworkSubmission): HomeworkSubmission {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_StudentProfile_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentProfile): StudentProfile {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_SubmissionStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmissionStatus): SubmissionStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        teacher: _TeacherProfile;
    } | {
        student: _StudentProfile;
    }]): {
    __kind__: "teacher";
    teacher: TeacherProfile;
} | {
    __kind__: "student";
    student: StudentProfile;
} | null {
    return value.length === 0 ? null : from_candid_variant_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudyStreak]): StudyStreak | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _SubmissionStatus;
    homeworkId: bigint;
    studentPrincipal: Principal;
    submittedAt: _Timestamp;
    submittedContent: string;
}): {
    id: bigint;
    status: SubmissionStatus;
    homeworkId: bigint;
    studentPrincipal: Principal;
    submittedAt: Timestamp;
    submittedContent: string;
} {
    return {
        id: value.id,
        status: from_candid_SubmissionStatus_n18(_uploadFile, _downloadFile, value.status),
        homeworkId: value.homeworkId,
        studentPrincipal: value.studentPrincipal,
        submittedAt: value.submittedAt,
        submittedContent: value.submittedContent
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    parent2Contact: [] | [string];
    principal: Principal;
    dateOfBirth: [] | [string];
    name: string;
    parent1Name: [] | [string];
    academicMedium: [] | [string];
    email: string;
    schoolAddress: [] | [string];
    bloodGroup: [] | [string];
    rollNumber: string;
    gender: [] | [string];
    schoolTiming: [] | [string];
    board: [] | [string];
    livingAddress: [] | [string];
    parent1Contact: [] | [string];
    className: string;
    parent2Name: [] | [string];
    schoolName: [] | [string];
}): {
    parent2Contact?: string;
    principal: Principal;
    dateOfBirth?: string;
    name: string;
    parent1Name?: string;
    academicMedium?: string;
    email: string;
    schoolAddress?: string;
    bloodGroup?: string;
    rollNumber: string;
    gender?: string;
    schoolTiming?: string;
    board?: string;
    livingAddress?: string;
    parent1Contact?: string;
    className: string;
    parent2Name?: string;
    schoolName?: string;
} {
    return {
        parent2Contact: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.parent2Contact)),
        principal: value.principal,
        dateOfBirth: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.dateOfBirth)),
        name: value.name,
        parent1Name: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.parent1Name)),
        academicMedium: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.academicMedium)),
        email: value.email,
        schoolAddress: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.schoolAddress)),
        bloodGroup: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.bloodGroup)),
        rollNumber: value.rollNumber,
        gender: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.gender)),
        schoolTiming: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.schoolTiming)),
        board: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.board)),
        livingAddress: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.livingAddress)),
        parent1Contact: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.parent1Contact)),
        className: value.className,
        parent2Name: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.parent2Name)),
        schoolName: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.schoolName))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_StudentProfile>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<StudentProfile>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n11(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_HomeworkSubmission>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<HomeworkSubmission>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n15(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    graded: null;
} | {
    submitted: null;
} | {
    pending: null;
}): SubmissionStatus {
    return "graded" in value ? SubmissionStatus.graded : "submitted" in value ? SubmissionStatus.submitted : "pending" in value ? SubmissionStatus.pending : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    teacher: _TeacherProfile;
} | {
    student: _StudentProfile;
}): {
    __kind__: "teacher";
    teacher: TeacherProfile;
} | {
    __kind__: "student";
    student: StudentProfile;
} {
    return "teacher" in value ? {
        __kind__: "teacher",
        teacher: value.teacher
    } : "student" in value ? {
        __kind__: "student",
        student: from_candid_StudentProfile_n3(_uploadFile, _downloadFile, value.student)
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Announcement;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Announcement;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _HomeworkAssignment;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: HomeworkAssignment;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ChatMessage;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ChatMessage;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _StudentProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: StudentProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_StudentProfile_n3(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _TeacherProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: TeacherProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _HomeworkSubmission;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: HomeworkSubmission;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_HomeworkSubmission_n16(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _TimetableEntry;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: TimetableEntry;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    teacher: null;
} | {
    unregistered: null;
} | {
    student: null;
}): UserRole {
    return "teacher" in value ? UserRole.teacher : "unregistered" in value ? UserRole.unregistered : "student" in value ? UserRole.student : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudentProfile>): Array<StudentProfile> {
    return value.map((x)=>from_candid_StudentProfile_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HomeworkSubmission>): Array<HomeworkSubmission> {
    return value.map((x)=>from_candid_HomeworkSubmission_n16(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
